env:
  global:
    - TIMEOUT=5000
addons:
  hosts:
  - localhost
language: java
script: ./gradlew clean build
jdk: openjdk11

branches:
  only:
  - master
  - feature/issue_25_robo4j_http_socket_update